// console.log(2 ==2);
// console.log(2=='2')
// console.log(1==true)
// console.log(0===false)
// console.log(NaN==NaN)
// console.log(0==="")
// console.log([]==="")
// console.log([]=="")
// console.log([5]=="5")
console.log([5]==[5])
